// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.FrontOffice
{
    [DbContext(typeof(FrontOfficeDbContext))]
    partial class FrontOfficeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("Domain.Entities.WFCaseLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinkType")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProcessMetaDataJson")
                        .HasColumnType("BLOB");

                    b.Property<Guid>("SourceAppId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceCaseId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceMainEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceMainEntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceWFClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetAppId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TargetCaseId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TargetMainEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetMainEntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetWFClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WFCaseLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
