// <auto-generated />
using System;
using Infrastructure.BackOffice.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BackOfficeDbContext))]
    [Migration("20250826093407_InitialCreate_BO")]
    partial class InitialCreate_BO
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("Domain.Entities.WFCaseLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LinkType")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProcessMetaDataJson")
                        .HasColumnType("BLOB");

                    b.Property<Guid>("SourceAppId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceCaseId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceMainEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceMainEntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceWFClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetAppId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TargetCaseId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TargetMainEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetMainEntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetWFClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("currentTaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WFCaseLinks");
                });

            modelBuilder.Entity("Domain.Entities.WorkflowEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkflowEntity", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
